### PR TITLE
Attempt to fix releases and huge artifact sizes

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Comment by srevinsaju** [comment]
~~I will wait to see if [this](https://github.com/srevinsaju/musicblocks-launcher/actions/runs/966786065) builds correctly and releases everything~~. Yes, it works as expected. Can merge.

**Comment by Clue88** [comment]
I only see one of the AppImages in the release – are the binaries for `aarch64` and `armv7l` there too?

**Comment by Clue88** [comment]
Though it also seems like all of the correct artifacts are built, uploaded, and released in the CI checks? Not sure why they aren't appearing in the release you sent me then.

**Comment by srevinsaju** [comment]
I found the bug, the `--arch` parameter was sent to the `./scripts/ci-appimage-patch.sh` instead. `x86_64` was hardcoded in the patch script. Now that we need to extract it. There is a lot of conflicting architecture names. :sweat:  

Working on it now ✨

**Comment by Clue88** [comment]
> Working on it now ✨

Great, thank you!

**Comment by srevinsaju** [comment]
Tested, @Clue88 can you checkout this one: https://github.com/srevinsaju/musicblocks-launcher/releases/tag/continuous

Looks like all the AppImage assets are now correctly uploaded ✨

**Comment by Clue88** [comment]
All looks good to me – thank you!

**Pull request merged**
