### PR TITLE
Merge upstream srevinsaju/musicblocks-app to sugarlabs/musicblocks-launcher

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Comment by srevinsaju** [comment]
Ready to merge :tada:

**Comment by srevinsaju** [comment]
@walterbender @Clue88 kindly review :smile:

**Comment by tchx84** [comment]
~~shouldn't we include the flatpak manifest (`org.sugarlabs.MusicBlocks.yaml`) here as well ?~~

Oh, nvm... it's there already.

**Comment by tchx84** [comment]
> ~shouldn't we include the flatpak manifest (`org.sugarlabs.MusicBlocks.yaml`) here as well ?~
> 
> Oh, nvm... it's there already.

I will need to try this later today / during the weekend, but it seems that the instructions for creating the Flatpak bundle are a bit disconnected from the other ones formats, e.g. the snap yaml uses `.deb` package, bur then the flatpak yaml uses appimage package.

It would be even better if there was a cohesive experience for building locally any of these packages, where someone can do common steps first and then just run specific steps for the format they are interested in.

Here an example of a flatpak package build from a .deb https://github.com/flathub/com.flashforge.FlashPrint/blob/master/com.flashforge.FlashPrint.json

**Comment by srevinsaju** [comment]
I do not know about the `flatpak` instructions, those are provided by @Clue88 , I can provide additional information about those on Snaps, Debs, AppImages and EXEs :smile:

**Comment by Clue88** [comment]
@srevinsaju I think this looks good, except some of the instructions from the README are missing in the updated version. As of right now, the Flatpak version relies on AppImage binaries due to some problems with installing Electron 9 offline (as is necessary for Flathub apps).

Thus, to update the Music Blocks Flatpak, I'd need to apply the patches in the `patches` directory (which fix some problems with exiting the app – it was creating an infinite loop that could only be exited by force-quitting the app when the dialog popped up asking if the user wanted to save their changes – as well as removing the javascript prompt during save). Then, I'd have to build a binary for each architecture, add them to a release on this repo, and then point the manifest on Flathub to the new binaries.

It's a little (a lot) clunky but it was the one solution I could find that went around the problems with Electron 9 itself and Flatpak. I don't know how the continuous release stuff works, but it seems like it could help with that? It's nice that the source code for the app is now all in this repo and it would be great if the steps I listed above (also in the original README under "Creating AppImage Binaries") could be automatically done whenever changes are made here. That way, I can have the Flatpak manifest just point to the continuously updated binaries here and updates could be made in just one location.

**Comment by Clue88** [comment]
Also, I have a Mac, so if you have instructions on how to get the .dmg, I can test that as well.

**Comment by Clue88** [comment]
> > ~shouldn't we include the flatpak manifest (`org.sugarlabs.MusicBlocks.yaml`) here as well ?~
> > Oh, nvm... it's there already.
> 
> I will need to try this later today / during the weekend, but it seems that the instructions for creating the Flatpak bundle are a bit disconnected from the other ones formats, e.g. the snap yaml uses `.deb` package, bur then the flatpak yaml uses appimage package.
> 
> It would be even better if there was a cohesive experience for building locally any of these packages, where someone can do common steps first and then just run specific steps for the format they are interested in.
> 
> Here an example of a flatpak package build from a .deb https://github.com/flathub/com.flashforge.FlashPrint/blob/master/com.flashforge.FlashPrint.json

That does seem like a better solution (and seems like a similar process to what I have with the AppImages). We'd just need to make sure the .deb package has all of the fixes necessary to work on Flatpak (see above re. the patches).

**Comment by tchx84** [comment]
> > > ~shouldn't we include the flatpak manifest (`org.sugarlabs.MusicBlocks.yaml`) here as well ?~
> > > Oh, nvm... it's there already.
> > 
> > 
> > I will need to try this later today / during the weekend, but it seems that the instructions for creating the Flatpak bundle are a bit disconnected from the other ones formats, e.g. the snap yaml uses `.deb` package, bur then the flatpak yaml uses appimage package.
> > It would be even better if there was a cohesive experience for building locally any of these packages, where someone can do common steps first and then just run specific steps for the format they are interested in.
> > Here an example of a flatpak package build from a .deb https://github.com/flathub/com.flashforge.FlashPrint/blob/master/com.flashforge.FlashPrint.json
> 
> That does seem like a better solution (and seems like a similar process to what I have with the AppImages). We'd just need to make sure the .deb package has all of the fixes necessary to work on Flatpak (see above re. the patches).

If the patches are targeted at javascript files, then you could apply them manually after the .deb are installed, in a post-install step.

**Comment by srevinsaju** [comment]
I already have patches which are a bunch of `sed` expressions, which rewrites the Musicblocks' logic of exiting. Musicblocks ask the user "You have unsaved changes". Clicking yes, you download the file. The Electron app will simple download the file, and the user will have no idea. For that reason, we have to run ./patch.sh, which is a shell script file. This helps to ask the user "Do you want to save the changes", and clicking yes will open a Gtk.FileChooser. If no is selected, the app quits.

**Comment by srevinsaju** [comment]
I already have patches which are a bunch of `sed` expressions, which rewrites the Musicblocks' logic of exiting. Musicblocks ask the user "You have unsaved changes". Clicking yes, you download the file. The Electron app will simple download the file, and the user will have no idea. For that reason, we have to run ./patch.sh, which is a shell script file. This helps to ask the user "Do you want to save the changes", and clicking yes will open a Gtk.FileChooser. If no is selected, the app quits.

Regarding the `deb`, I have tested the `deb` on Xubuntu 18.04, Ubuntu 20.04 and 20.10

**Comment by srevinsaju** [comment]
I see that in the documentation for creating flatpaks by @Clue88, there is no mention of running `patch.sh` and therefore you face that weird bug. Running `patch.sh` would automatically fix the bugs you mentioned above.

**Comment by srevinsaju** [comment]
https://github.com/sugarlabs/musicblocks-launcher/pull/6/commits/7495f1bf95d05f07109e1b189edcf4fee7f9e396 enables the CI to automatically build musicblocks debs from source after patching on every commit. Let me know if I can provide any other feature / ci

**Comment by Clue88** [comment]
@srevinsaju Hi Srevin – The CI features are great. If I'm understanding everything correctly, this means that I can point the Flatpak manifest to the continuous releases and get AppImage binaries from there. Only thing I need is for AppImages to be built for arm and aarch64 to comply with Flathub guidelines. Thanks!

**Comment by Clue88** [comment]
Other minor thing for consistency – Music Blocks should be spelled "MusicBlocks" (capital 'B') in `package.json` and elsewhere. Also, I believe the instructions for AppImages in the README are outdated (they don't match the instructions used for CI) but I can fix that part later.

**Comment by srevinsaju** [comment]
> @srevinsaju Hi Srevin – The CI features are great. If I'm understanding everything correctly, this means that I can point the Flatpak manifest to the continuous releases and get AppImage binaries from there. Only thing I need is for AppImages to be built for arm and aarch64 to comply with Flathub guidelines. Thanks!

I do not know about `arm` and `aarch64`, we are migrating from `Travis` to `GitHub Actions` on `appimagetool` (the tool used to create appimages), first; so first I will work on `arm` and `aarch64` support on https://github.com/probonopd/go-appimage/pull/106, so until then :smile: 

> Other minor thing for consistency – Music Blocks should be spelled "MusicBlocks" (capital 'B') in package.json and elsewhere. Also, I believe the instructions for AppImages in the README are outdated (they don't match the instructions used for CI) but I can fix that part later.

Kindly base your PRs on `srevinsaju:big-merge` so I can add them to this PR after review

**Comment by Clue88** [comment]
@srevinsaju Apologies for the slow development – I got bogged down by schoolwork but I'll be working on this more now. I added CI instructions for `arm` and `aarch64` to create AppImages that can be used by the Flatpak. I was able to test the steps for `aarch64` but I don't have a computer with the `armv7l` architecture.

**Comment by Clue88** [comment]
From what I can see, this should be ready to merge. I can then clean up and update the Flatpak manifest and documentation accordingly.

**Review by Clue88 — APPROVED** [review]

**Comment by Clue88** [comment]
Update re. MacOS – seems to work fine for me on my Mac, both on x86 and m1.

**Pull request merged**
