### PR TITLE
feat: upgrade electron to 13.x

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Review by Clue88 — APPROVED** [review]

**Comment by Clue88** [comment]
@srevinsaju Looks great! I saw that you marked this as ready for review but you added a lot more commits – is this ready for merge?

**Comment by srevinsaju** [comment]
> @srevinsaju Looks great! I saw that you marked this as ready for review but you added a lot more commits – is this ready for merge?

Yep, I was trying to fix the broken CI. Now it's done!

**Comment by srevinsaju** [comment]
Wow, that was fast :rocket:

**Comment by Clue88** [comment]
Thank you for your help!!

**Comment by srevinsaju** [comment]
Ouch, I think I messed up the release part :thinking: 

Update: trying to debug :man_technologist: 

Update 2: Fixed. Awaiting #18  merge.

**Pull request merged**
